### ISSUE TITLE
Potential gas limit issue in `execute` function.

### ISSUE THREAD

**Issue by poodaydreamer** [brumeproject/eth#12]
The execute function iterates through an array of transactions and executes them sequentially. 
If the array is large or the transactions are complex, it could exceed the gas limit, causing the transaction to fail.

**Comment by hazae41** [comment]
Thanks, do you have a fix for that?

**Comment by poodaydreamer** [comment]
@hazae41 

As long as this function is "onlyOwner" function, I think this is not serious issue and it can be considered as fine. 

Actually, I can see OpenZeppelin Governor contract is written in the same way.
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/governance/Governor.sol#L439

Feel free to close this issue.

**Comment by hazae41** [comment]
How is OpenZeppelin fixing this? It looks like the same as we have

**Comment by poodaydreamer** [comment]
Hey @hazae41 Sorry for your confusion, I updated the comment.
