### ISSUE TITLE
"steal" function is needless

### ISSUE THREAD

**Issue by poodaydreamer** [brumeproject/eth#13]
Instead of using [steal](https://github.com/brumewallet/onchain/blob/e6e93e79ec0e19db21e046a539fa34120848ef44/src/Governance.sol#L158) function, maybe we can block token transfer if destination address has more than available balance (25%)

**Comment by hazae41** [comment]
Thanks, we want to block someone from proposing if he has >25%, blocking transfers won't block proposing
