### ISSUE TITLE
Vote Result check is missing in execute function

### ISSUE THREAD

**Issue by poodaydreamer** [brumeproject/eth#14]
https://github.com/brumewallet/onchain/blob/e6e93e79ec0e19db21e046a539fa34120848ef44/src/Governance.sol#L209

Right now, we only check if there were certain period of delay after proposed but it doesn't have any logic to check the Voting result.

**Comment by hazae41** [comment]
This is normal, the result is implicitly true if the proposal hasn't been canceled/replaced, the only way to refuse a proposal is either to replace the owner (governance vote) or to convince him to change his proposal (market vote)
